# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49f63d719e8d078280cf9c2f48f6e82d7bb1e7eced1855b2bef09b8727a257131eb7b64ca57a59e7e2b8d5bbcaf45110439f245689230c101ca5fae0776ef7c5

test:
  secret_key_base: 685f55e471113e0da3c56efb8019301485cedb5e77cc39b60c3933b830ed6188a7735bee1e5c9679edfe743761cfbe0353eaddd737e62bd6def9cd7ff32e1993

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
